version: '3.8'

services:
  quantx-engine:
    build: .
    container_name: quantx-engine
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - INITIAL_CAPITAL=1000000
      - MAX_POSITION_SIZE=100000
      - RISK_LIMIT_DAILY_LOSS=50000
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8080:8080"
    networks:
      - quantx-network
    healthcheck:
      test: ["CMD", "pgrep", "quantx_engine"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: quantx-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - quantx-network
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    container_name: quantx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quantx_engine
      POSTGRES_USER: quantx
      POSTGRES_PASSWORD: quantx_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quantx-network

  prometheus:
    image: prom/prometheus:latest
    container_name: quantx-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - quantx-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: quantx-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - quantx-network

volumes:
  redis-data:
  postgres-data:
  prometheus-data:
  grafana-data:

networks:
  quantx-network:
    driver: bridge
